# Generated by Django 4.2.4 on 2023-12-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solusoft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='rut',
            field=models.CharField(default='12345678K', max_length=9),
        ),
    ]
